### ISSUE TITLE
task01/ Nav 컴포넌트 뼈대 작성 

### ISSUE THREAD

**Issue by Achates09** [codestates/Hidden_Track#1]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: Nav 컴포넌트 구성

### TODO
1. [x] Logo 클릭시 메인 페이지 이동
2. [x] Search 컴포넌트(자식)
3. [x] 로그인 버튼
4. [x] 프로필 사진(로그인시 햄버거바 역할)
5. [ ] SideBar 컴포넌트(자식)
