### ISSUE TITLE
task32 / Sidebar 기본 틀 구현

### ISSUE THREAD

**Issue by James940522** [codestates/Hidden_Track#106]
### ISSUE
- Group: `client`, `server`, `sr`
- Type: `feature`, `bug`, `delete`
- Detail: 

### TODO
1. [x]  redux 상태 값 받아오기
2. [x]  재생목록, 오디오 플레이어 렌더
3. [x]  state를 이용한 기본 렌더 구현
