### ISSUE TITLE
task10 / Mypage(회원정보수정) 뼈대 작성

### ISSUE THREAD

**Issue by Achates09** [codestates/Hidden_Track#11]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 

### TODO
1. [x] 제목({아이디}님의 회원정보)
2. [x] 프로필 이미지 미리보기, 변경/삭제 버튼(자식)
3. [x] 비밀번호/비밀번호 확인, 변경 버튼(자식)
4. [x] 닉네임, 중복확인 버튼, 변경 버튼(자식)
5. [x] 아티스트 계정으로 전환하기(checkbox 버튼)(이하 모두 자식)
6. [x] 소속사, 데뷔연월(select: option), 이메일
7. [x] 계정전환 버튼
8. [x] 회원 탈퇴 버튼(클릭시 회원 탈퇴 확인 모달창)
