### ISSUE TITLE
task37 / sidebar 구현

### ISSUE THREAD

**Issue by James940522** [codestates/Hidden_Track#131]
### ISSUE
- Group: `client`, `server`, `sr`
- Type: `feature`, `bug`, `delete`
- Detail: 

### TODO
1. [x] 비주얼라이져 state 핸들링과 동일
2. [x] 버튼 누를시 애니매이션 구현
3. [x] 레이아웃 배치 및 기본 css 작성
