### ISSUE TITLE
task15 / Main 메인페이지 뼈대 작성

### ISSUE THREAD

**Issue by Achates09** [codestates/Hidden_Track#16]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 

### TODO
1. [x] 인기/최신 차트(자식)
2. [x] 추천 차트(자식)
3. [x] 장르 컴포넌트(자식)
4. [x] 해시태그 컴포넌트(자식)
