### ISSUE TITLE
task17 / Main 추천 차트 구현

### ISSUE THREAD

**Issue by Achates09** [codestates/Hidden_Track#18]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 

### TODO
1. [x] 최초 랜더시(useEffect) axios 요청(해당 정보 받아옴)
2. [x] 썸네일, 타이틀, 아티스트명
3. [x] 클릭시 음원 상세페이지 이동(해당 음원 정보 axios 요청)
