### ISSUE TITLE
task20 / 검색 결과 페이지 구현

### ISSUE THREAD

**Issue by Achates09** [codestates/Hidden_Track#21]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 

### TODO
1. [x] 검색 결과가 없을 경우 안내 메시지 랜더링
2. [x] 검색 결과 map 랜더링
3. [x] 음원 클릭시 상세 음원 정보 axios 요청
4. [x] 요청 성공시 상세 음원 정보 전역 상태에 저장
5. [x] 저장 후 음원 상세 페이지로 이동
6. [x] 요청 실패시 함수 종료 및 알림 메시지
