### ISSUE TITLE
task02 / 로그인 모달창 구현

### ISSUE THREAD

**Issue by Achates09** [codestates/Hidden_Track#3]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: 

### TODO
1. [x] Logo
2. [ ] 아이디(유효성 검사)
3. [ ] 비밀번호(유효성 검사)
4. [x] 회원가입 페이지 이동 버튼
5. [x] 로그인 버튼
6. [ ] 소셜로그인 버튼
7. [x] 모달창 닫기 버튼(X)
8. [ ] 로그인 상태유지(advanced)
