### ISSUE TITLE
task30 / 비주얼라이져 랜덤 재생 기능 구현

### ISSUE THREAD

**Issue by James940522** [codestates/Hidden_Track#97]
### ISSUE
- Group: `client`, `server`, `sr`
- Type: `feature`, `bug`, `delete`
- Detail: 

### TODO
1. [x] 랜덤 재생 상태 여부에 따라 순차 재생 / 랜덤 재생 구현
2. [x] 랜덤 인덱스 생성 함수 구현
3. [x] 이전곡 버튼 누를시 필요한 알고리즘 구현 (stack)
